version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root